In [30]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import os

In [31]:
os.getcwd()

'C:\\AI_Program_Capstone\\Capstone3_UsedCarsData'

In [32]:
os.chdir('C:\\AI_Program_Capstone\\Capstone3_UsedCarsData')

In [33]:
os.getcwd()

'C:\\AI_Program_Capstone\\Capstone3_UsedCarsData'

In [34]:
df_car_sales_trans = pd.read_csv('Car_sales_transactions.csv',header=0,sep=',',encoding='latin')

#### Read the Car_sales_transactions.csv file and store the result to df_car_sales_trans dataframe

In [35]:
df_car_sales_status = pd.read_csv('Sales_Status.csv',header=0,sep=',',encoding='latin')

#### Read the Car_sales_status.csv file and store the result to df_car_sales_status dataframe

In [36]:
df_car_sales_trans.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats'],
      dtype='object')

In [37]:
df_car_sales_status.columns

Index(['Sales_ID', 'Sold'], dtype='object')

In [38]:
df_car_sales_rep = pd.merge(df_car_sales_trans,df_car_sales_status,how='left',left_on='Sales_ID',right_on='Sales_ID')

#### Merged df_car_sales_trans and df_car_sales_status dataframes using left join on Sales_ID column ####

In [39]:
df_car_sales_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold'],
      dtype='object')

In [40]:
df_car_sales_rep['Sold_Mapped'] = (df_car_sales_rep['Sold']=='Y').map({True:1, False:0})

#### Mapped all the values('Y'/'N') of Sold Column to 1 and 0 and stored in Sold_Mapped column of df_car_sales_rep dataframe####

In [41]:
df_car_sales_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped'],
      dtype='object')

In [42]:
df_car_sales_rep.shape

(7906, 18)

#### Verified number of rows matching with Car_sales_transactions.csv file ####

In [43]:
df_city = pd.read_excel('City_Master.xlsx',header=0)

#### Read the City_Master.xlsx file and store the result to df_city dataframe ####

In [44]:
df_state = pd.read_excel('State_Master.xlsx',header=0)

#### Read the State_Master.xlsx file and store the result to df_state dataframe ####

In [45]:
df_rep_with_state= pd.merge(df_car_sales_rep,df_state,how='left',left_on='State_Code',right_on='State_Code')

#### Merge df_car_sales_rep and  df_state using left join on State_Code and stored the result to df_rep_with_state dataframe

In [46]:
df_used_cars_rep = pd.merge(df_rep_with_state,df_city,how='left',left_on='City_Code',right_on='City_Code')

#### Merge df_car_sales_rep and  df_state using left join on State_Code and stored the result to df_rep_with_state dataframe

In [47]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'State_Code_y'],
      dtype='object')

In [48]:
df_used_cars_rep.head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Owner,Mileage,Engine,Max_Power,Seats,Sold,Sold_Mapped,State_Name,City_Name,State_Code_y
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,...,First Owner,23.4 kmpl,1248 CC,74 bhp,5,Y,1,Maharashtra,Mumbai,ST15
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,...,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5,Y,1,Jharkhand,Ranchi,ST11
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,...,Third Owner,17.7 kmpl,1497 CC,78 bhp,5,Y,1,Uttar Pradesh,Noida,ST28
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,...,First Owner,23.0 kmpl,1396 CC,90 bhp,5,Y,1,Uttarakhand,Dehradun,ST27
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,...,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5,Y,1,Tamil Nadu,Chennai,ST24

#### Displayed first 5 rows of df_used_cars_rep dataframe ####

In [50]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'State_Code_y'],
      dtype='object')

In [51]:
df_used_cars_rep.drop('State_Code_y',axis=True,inplace=True)

#### dropped the redundant column State_Code_y from the df_used_cars_rep dataframe ####

In [52]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name'],
      dtype='object')

In [53]:
df_region_state = pd.read_excel('Region_State_Mapping.xlsx',header=0)

#### read the file Region_State_Mapping.xlsx file and stored to df_region_state dataframe ####

In [54]:
df_region_state.columns

Index(['Region_Code', 'State_Code'], dtype='object')

In [55]:
df_used_cars_rep = pd.merge(df_used_cars_rep,df_region_state,how='left',left_on='State_Code_x',right_on='State_Code')

#### merged df_used_cars_rep dataframe and df_region_state using left join on  State_Code column ####

In [56]:
df_used_cars_rep.head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Mileage,Engine,Max_Power,Seats,Sold,Sold_Mapped,State_Name,City_Name,Region_Code,State_Code
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,...,23.4 kmpl,1248 CC,74 bhp,5,Y,1,Maharashtra,Mumbai,R3,ST15
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,...,21.14 kmpl,1498 CC,103.52 bhp,5,Y,1,Jharkhand,Ranchi,R2,ST11
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,...,17.7 kmpl,1497 CC,78 bhp,5,Y,1,Uttar Pradesh,Noida,R1,ST28
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,...,23.0 kmpl,1396 CC,90 bhp,5,Y,1,Uttarakhand,Dehradun,R1,ST27
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,...,16.1 kmpl,1298 CC,88.2 bhp,5,Y,1,Tamil Nadu,Chennai,R4,ST24

In [57]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'Region_Code', 'State_Code'],
      dtype='object')

In [58]:
df_used_cars_rep.columns[-1]

'State_Code'

In [60]:
df_used_cars_rep.drop(df_used_cars_rep.columns[-1], axis = 1, inplace = True)

#### dropped the redundant column State_code from df_used_cars_rep repository ####

In [61]:
df_used_cars_rep.head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Owner,Mileage,Engine,Max_Power,Seats,Sold,Sold_Mapped,State_Name,City_Name,Region_Code
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,...,First Owner,23.4 kmpl,1248 CC,74 bhp,5,Y,1,Maharashtra,Mumbai,R3
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,...,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5,Y,1,Jharkhand,Ranchi,R2
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,...,Third Owner,17.7 kmpl,1497 CC,78 bhp,5,Y,1,Uttar Pradesh,Noida,R1
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,...,First Owner,23.0 kmpl,1396 CC,90 bhp,5,Y,1,Uttarakhand,Dehradun,R1
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,...,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5,Y,1,Tamil Nadu,Chennai,R4

#### diplayed first 5 rows after removing redundant columns ####

In [62]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'Region_Code'],
      dtype='object')

In [63]:
df_region_master = pd.read_excel('Region_Master.xlsx',header=0)

#### read the Region_Master.xlsx file and store it in df_region_master dataframe ####

In [64]:
df_used_cars_rep = pd.merge(df_used_cars_rep,df_region_master,how='left',left_on='Region_Code',right_on='Region_Code')

#### Merge df_used_cars_rep and df_region_master dataframes using left join and store it again in df_used_cars_rep dataframe

In [65]:
df_used_cars_rep.shape

(7906, 22)

In [66]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'Region_Code', 'Region'],
      dtype='object')

In [67]:
df_used_cars_rep.head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Mileage,Engine,Max_Power,Seats,Sold,Sold_Mapped,State_Name,City_Name,Region_Code,Region
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,...,23.4 kmpl,1248 CC,74 bhp,5,Y,1,Maharashtra,Mumbai,R3,West
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,...,21.14 kmpl,1498 CC,103.52 bhp,5,Y,1,Jharkhand,Ranchi,R2,East
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,...,17.7 kmpl,1497 CC,78 bhp,5,Y,1,Uttar Pradesh,Noida,R1,Central
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,...,23.0 kmpl,1396 CC,90 bhp,5,Y,1,Uttarakhand,Dehradun,R1,Central
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,...,16.1 kmpl,1298 CC,88.2 bhp,5,Y,1,Tamil Nadu,Chennai,R4,South

In [68]:
df_used_cars_rep['Name'].head(5)

0          Maruti Swift Dzire VDI
1    Skoda Rapid 1.5 TDI Ambition
2        Honda City 2017-2020 EXi
3       Hyundai i20 Sportz Diesel
4          Maruti Swift VXI BSIII
Name: Name, dtype: object

In [69]:
df_used_cars_rep['Brand'] = df_used_cars_rep['Name'].str.split(' ', 1).str[0]

#### added Brand column to df_used_cars_rep dataframe####

In [70]:
df_used_cars_rep.head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Engine,Max_Power,Seats,Sold,Sold_Mapped,State_Name,City_Name,Region_Code,Region,Brand
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,...,1248 CC,74 bhp,5,Y,1,Maharashtra,Mumbai,R3,West,Maruti
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,...,1498 CC,103.52 bhp,5,Y,1,Jharkhand,Ranchi,R2,East,Skoda
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,...,1497 CC,78 bhp,5,Y,1,Uttar Pradesh,Noida,R1,Central,Honda
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,...,1396 CC,90 bhp,5,Y,1,Uttarakhand,Dehradun,R1,Central,Hyundai
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,...,1298 CC,88.2 bhp,5,Y,1,Tamil Nadu,Chennai,R4,South,Maruti

In [72]:
#No of cars sold brandwise on each region by brand
df_used_cars_rep.query("Sold == 'Y'").groupby(['Brand'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)

       Brand  Total_Sold
17    Maruti         597
9    Hyundai         332
16  Mahindra         201
23      Tata         178
24    Toyota         126

#### Top 5 Brand solds across the regions ####

In [75]:
#No of cars sold brandwise on each region by brand
df_used_cars_rep.query("Sold == 'Y'").groupby(['Brand','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(15)

      Brand  City_Name  Total_Sold
235  Maruti  Mangalore          32
225  Maruti   Dehradun          30
243  Maruti      Surat          27
228  Maruti  Hyderabad          25
232  Maruti      Kochi          25
236  Maruti     Mumbai          24
246  Maruti    Vellore          24
227  Maruti    Gangtok          23
237  Maruti     Mysore          23
239  Maruti      Noida          23
226  Maruti      Delhi          22
223  Maruti    Chennai          21
245  Maruti   Vadodara          21
242  Maruti     Ranchi          20
240  Maruti      Patna          20

#### first 15 rows who sold across city names ####

In [78]:
#No of cars sold brandwise on East region (Maruti dominated refer below query for specific brands)
df_used_cars_rep.query("Sold == 'Y' & Region=='East'").groupby(['Brand','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)
#df_used_cars_rep.query("Sold == 'Y' & Region=='East'").groupby(['Brand','Name','Region','State_Name','City_Name'],as_index=False).size().sort_values('size',ascending=False).head(15)

     Brand Region   State_Name     City_Name  Total_Sold
38  Maruti   East        Bihar         Patna          20
42  Maruti   East  West Bengal       Kolkata          20
40  Maruti   East    Jharkhand        Ranchi          20
41  Maruti   East       Odisha  Bhubaneshwar          15
39  Maruti   East    Jharkhand    Jamshedpur          12

####  maximum number of cars sold by different brand with East Region and State names ####

In [80]:
#No of cars sold brandwise on West region (Maruti dominated refer below query for specific brands)
df_used_cars_rep.query("Sold == 'Y' & Region=='West'").groupby(['Brand','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)
#df_used_cars_rep.query("Sold == 'Y' & Region=='West'").groupby(['Brand','Name','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(15)

     Brand Region   State_Name   City_Name  Total_Sold
39  Maruti   West      Gujarat       Surat          27
42  Maruti   West  Maharashtra      Mumbai          24
40  Maruti   West      Gujarat    Vadodara          21
38  Maruti   West      Gujarat   Ahmedabad          18
41  Maruti   West  Maharashtra  Aurangabad          17

####  maximum number of cars sold by different brand with West Region and State names ####

In [81]:
#No of cars sold brandwise on North region (Maruti dominated refer below query for specific brands)
df_used_cars_rep.query("Sold == 'Y' & Region=='North'").groupby(['Brand','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)
#df_used_cars_rep.query("Sold == 'Y' & Region=='North'").groupby(['Brand','Name','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)

      Brand Region State_Name City_Name  Total_Sold
24   Maruti  North      Delhi     Delhi          22
25   Maruti  North     Punjab  Ludhiana          17
15  Hyundai  North      Delhi     Delhi          15
26   Maruti  North  Rajasthan    Jaipur          13
35   Toyota  North      Delhi     Delhi          11

####  maximum number of cars sold by different brand with North Region and State names ####

In [84]:
#No of cars sold brandwise on South region (Maruti dominated refer below query for specific brands)
df_used_cars_rep.query("Sold == 'Y' & Region=='South'").groupby(['Brand','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)
#df_used_cars_rep.query("Sold == 'Y' & Region=='North'").groupby(['Brand','Name','Region','State_Name','City_Name'],as_index=False).size().rename(columns={'size':'Total_Sold'}).sort_values('Total_Sold',ascending=False).head(5)

     Brand Region  State_Name  City_Name  Total_Sold
81  Maruti  South   Karnataka  Mangalore          32
88  Maruti  South   Telangana  Hyderabad          25
83  Maruti  South      Kerala      Kochi          25
87  Maruti  South  Tamil Nadu    Vellore          24
82  Maruti  South   Karnataka     Mysore          23

####  maximum number of cars sold by different brand with South Region and State names ####

In [87]:
#TO GET RANGE OF KM DRIVEN AS PER USER'S INTEREST:
#df_car_sales_rep['Sold_Mapped'] = (df_car_sales_rep['Sold']=='Y').map({True:1, False:0})
#km_Driven_range = [5000, 10000, 20000, 40000, 80000,160000,200000,250000,300000]
km_Driven_range = [0,5000, 10000, 20000, 40000, 80000,160000,200000,250000,np.inf]
#names = ['<5K', '10K-20K', '20K-40K', '40K-80K', '80K-160K','160K-200K','200K-250K','250K+']
names = ['0-5K', '5K-10K', '10K-20K', '20K-40K', '40K-80K','80K-160K','160K-200K','200K-250K','250K+']
df_used_cars_rep['km_Driven_range'] = pd.cut(df_used_cars_rep['km_Driven'], km_Driven_range, labels=names)
#d = dict(enumerate(names, 1))

#df['AgeRange'] = np.vectorize(d.get)(np.digitize(df['Age'], bins))

#df_used_cars_rep['km_Driven_range'] = np.vectorize(d.get)(np.digitize(df_used_cars_rep['km_Driven'], km_Driven_range))

#### divided km_driven column by range and stored it in km_Driven_range column of df_used_cars_rep dataframe ####

In [88]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'Region_Code', 'Region',
       'Brand', 'km_Driven_range'],
      dtype='object')

In [89]:
df_used_cars_rep.shape

(7906, 24)

In [90]:
df_used_cars_rep[df_used_cars_rep['km_Driven']==20000].head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Max_Power,Seats,Sold,Sold_Mapped,State_Name,City_Name,Region_Code,Region,Brand,km_Driven_range
127,133,Lexus ES 300h,2019,5150000,20000,CT05,ST25,500004,Petrol,Dealer,...,214.56 bhp,5,Y,1,Telangana,Hyderabad,R4,South,Lexus,10K-20K
163,170,Maruti Ertiga BSIV ZXI Plus,2016,850000,20000,CT15,ST20,751022,Petrol,Individual,...,91.1 bhp,7,Y,1,Odisha,Bhubaneshwar,R2,East,Maruti,10K-20K
200,209,Maruti Swift Dzire VXI 1.2,2017,550000,20000,CT25,ST01,524225,Petrol,Individual,...,81.80 bhp,5,Y,1,Andhra Pradesh,Nellore,R4,South,Maruti,10K-20K
201,210,Maruti Alto 800 LXI,2018,270000,20000,CT18,ST21,141003,Petrol,Individual,...,47.3 bhp,5,Y,1,Punjab,Ludhiana,R5,North,Maruti,10K-20K
203,212,Maruti Swift VXI Optional,2017,500000,20000,CT18,ST21,141003,Petrol,Individual,...,81.80 bhp,5,Y,1,Punjab,Ludhiana,R5,North,Maruti,10K-20K

#### verified km_driven_range logic with 20000 kms test case ####

In [218]:
#df_used_cars_rep.drop(['km_Driven_range'],axis=1,inplace=True)

In [91]:
# TO GET MODEL BASED ON USER'S INTEREST:
car_model_range = [0,1999,2005, 2011, 2015,2018,np.inf]
names = ['Antique(upto 1999)', 'Very Old(2000-2005)', 'Old(2006-2011)','Moderate(2012-2015)','Fair(2016-2018)','New(2019+)']
df_used_cars_rep['car_model_range'] = pd.cut(df_used_cars_rep['Year'], car_model_range, labels=names)

#### divided year column by range and stored it in car_model_range of df_used_cars_rep dataframe ####

In [92]:
df_used_cars_rep.columns

Index(['Sales_ID', 'Name', 'Year', 'Selling_Price', 'km_Driven', 'City_Code',
       'State_Code_x', 'Postal_Code', 'Fuel', 'Seller_Type', 'Transmission',
       'Owner', 'Mileage', 'Engine', 'Max_Power', 'Seats', 'Sold',
       'Sold_Mapped', 'State_Name', 'City_Name', 'Region_Code', 'Region',
       'Brand', 'km_Driven_range', 'car_model_range'],
      dtype='object')

In [93]:
df_used_cars_rep[df_used_cars_rep['Year']==2005].head(5)

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code_x,Postal_Code,Fuel,Seller_Type,...,Seats,Sold,Sold_Mapped,State_Name,City_Name,Region_Code,Region,Brand,km_Driven_range,car_model_range
11,12,Maruti Zen LX,2005,92000,100000,CT25,ST01,524225,Petrol,Individual,...,5,Y,1,Andhra Pradesh,Nellore,R4,South,Maruti,80K-160K,Very Old(2000-2005)
178,185,Honda City 1.5 EXI,2005,100000,120000,CT13,ST04,800002,Petrol,Individual,...,5,Y,1,Bihar,Patna,R2,East,Honda,80K-160K,Very Old(2000-2005)
185,192,Maruti Zen LXI,2005,85000,90000,CT14,ST07,395007,Petrol,Individual,...,5,Y,1,Gujarat,Surat,R3,West,Maruti,80K-160K,Very Old(2000-2005)
189,196,Hyundai Getz GLS,2005,65000,86000,CT14,ST07,395007,Petrol,Individual,...,5,Y,1,Gujarat,Surat,R3,West,Hyundai,80K-160K,Very Old(2000-2005)
274,285,Maruti Alto LX,2005,110000,45000,CT01,ST15,400001,Petrol,Individual,...,5,Y,1,Maharashtra,Mumbai,R3,West,Maruti,40K-80K,Very Old(2000-2005)

#### verified car_model_Range logic with 2005 year test case ####

In [244]:
#df_used_cars_rep.drop(['car_model_range'],axis=1,inplace=True)

#df_used_cars_rep.dtypes
df_used_cars_rep['approx_Mileage'] = df_used_cars_rep['Mileage'].str.split(' ', 1).str[0].astype('float64').apply(np.ceil)

#### added approx_Mileage column by taking ceil function and stored it in df_used_cars_rep dataframe ####

In [98]:
df_used_cars_rep['approx_Mileage'] = df_used_cars_rep['Mileage'].astype('str')

#### changed the datatype of car_model_range to string ####

In [258]:
df_used_cars_rep['km_Driven_range'] = df_used_cars_rep['km_Driven_range'].astype('object')

In [ ]:
#### changed the datatype of km_Driven_range to object ####

In [259]:
df_used_cars_rep['car_model_range'] = df_used_cars_rep['car_model_range'].astype('object')

#### changed the datatype of car_model_range to object ####

In [260]:
df_used_cars_rep.dtypes

Sales_ID             int64
Name                object
Year                 int64
Selling_Price      float64
km_Driven            int64
City_Code           object
State_Code_x        object
Postal_Code          int64
Fuel                object
Seller_Type         object
Transmission        object
Owner               object
Mileage             object
Engine              object
Max_Power           object
Seats                int64
Sold                object
Sold_Mapped          int64
State_Name          object
City_Name           object
Region_Code         object
Region              object
Brand               object
km_Driven_range     object
car_model_range     object
approx_Mileage      object
dtype: object

In [261]:
#Minimum Selling price for different brands(Considering all models) in all region for sold models:

paramter_check = ['Brand','Year','Name','Region','State_Name','City_Name','Seller_Type','km_Driven','Fuel','Engine','Seats','Transmission','Owner','Mileage','Max_Power']
df_min_selling_price = df_used_cars_rep.query("Sold == 'Y'").groupby(paramter_check,as_index=False).agg({'Selling_Price':np.min}).rename(columns={'Selling_Price':'Min_Selling_Price_in_lakhs'}).sort_values(by=['Name','km_Driven'],ascending=[True,True])
#df_used_cars_rep.query("Sold == 'Y' & Region=='East'").groupby(['Brand','Name','Region','State_Name','City_Name'],as_index=False).size().sort_values('size',ascending=False).head(15)

#### Minimum Selling price required for different brands(Considering all models) in all region for sold models ####

In [262]:
df_min_selling_price.Min_Selling_Price_in_lakhs = df_min_selling_price.Min_Selling_Price_in_lakhs/100000

#### divided with 100000 to convert  in terms of lakhs ####

In [263]:
"""
km_Driven_range = [0,5000, 10000, 20000, 40000, 80000,160000,200000,250000,np.inf]
#names = ['<5K', '10K-20K', '20K-40K', '40K-80K', '80K-160K','160K-200K','200K-250K','250K+']
names = ['0-5K', '5K-10K', '10K-20K', '20K-40K', '40K-80K','80K-160K','160K-200K','200K-250K','250K+']
df_min_selling_price['km_Driven_range'] = pd.cut(df_min_selling_price['km_Driven'], km_Driven_range, labels=names)
""""

In [264]:
"""

car_model_range = [0,1999,2005, 2011, 2015,2018,np.inf]

names = ['Antique(upto 1999)', 'Very Old(2000-2005)', 'Old(2006-2011)','Moderate(2012-2015)','Fair(2016-2018)','New(2019+)']
df_min_selling_price['car_model_range'] = pd.cut(df_min_selling_price['Year'], car_model_range, labels=names)

"""

In [265]:
df_min_selling_price['approx_Mileage'] = df_min_selling_price['Mileage'].str.split(' ', 1).str[0].astype('float64').apply(np.ceil)

#### added approx_Mileage column to df_min_selling_price dataframe ####

In [266]:
df_min_selling_price['approx_Mileage'] = df_min_selling_price['approx_Mileage'].astype('str')

In [267]:
df_min_selling_price.km_Driven_range = df_min_selling_price.km_Driven_range.astype('object')

In [268]:
df_min_selling_price.car_model_range = df_min_selling_price.car_model_range.astype('object')

In [206]:
df_min_selling_price.columns

Index(['Brand', 'Year', 'Name', 'Region', 'State_Name', 'City_Name',
       'Seller_Type', 'km_Driven', 'Fuel', 'Engine', 'Seats', 'Transmission',
       'Owner', 'Mileage', 'Max_Power', 'Min_Selling_Price_in_lakhs',
       'km_Driven_range', 'car_model_range', 'approx_Mileage'],
      dtype='object')

In [270]:
df_min_selling_price.head(5)

,Brand,Year,Name,Region,State_Name,City_Name,Seller_Type,km_Driven,Fuel,Engine,Seats,Transmission,Owner,Mileage,Max_Power,Min_Selling_Price_in_lakhs,km_Driven_range,car_model_range,approx_Mileage
3,Audi,2014,Audi A4 2.0 TDI,East,Jharkhand,Ranchi,Individual,44000,Diesel,1968 CC,5,Automatic,Second Owner,16.55 kmpl,147.51 bhp,16.00000,40K-80K,Moderate(2012-2015),17.0
1,Audi,2013,Audi A6 2.0 TDI Design Edition,West,Gujarat,Ahmedabad,Dealer,50000,Diesel,1968 CC,5,Automatic,First Owner,18.53 kmpl,187.74 bhp,16.89999,40K-80K,Moderate(2012-2015),19.0
2,Audi,2013,Audi A6 2.0 TDI Technology,West,Gujarat,Ahmedabad,Dealer,33900,Diesel,1968 CC,5,Automatic,Second Owner,17.68 kmpl,174.33 bhp,17.50000,20K-40K,Moderate(2012-2015),18.0
5,Audi,2017,Audi Q3 2.0 TDI Quattro Premium Plus,South,Andhra Pradesh,Nellore,Dealer,22000,Diesel,1968 CC,5,Automatic,First Owner,15.73 kmpl,174.33 bhp,28.25000,20K-40K,Fair(2016-2018),16.0
0,Audi,2011,Audi Q5 2.0 TDI,North,Delhi,Delhi,Individual,120000,Diesel,1968 CC,5,Automatic,First Owner,12.8 kmpl,167.6 bhp,13.00000,80K-160K,Old(2006-2011),13.0

In [287]:
# Big Brands Analysis ('BMW','Audi')... first preference is Km_Driven...almost every car is Diesel
#index_data = ['Brand','Year','Name','Region','State_Name','City_Name','km_Driven','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
index_data = ['Brand','Year','Name','km_Driven','Seller_Type','Owner','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
df_check_brand_min_Selling_price = df_min_selling_price.query("Brand=='Audi' | Brand=='BMW'")
pd.pivot_table(df_check_brand_min_Selling_price,values=['Min_Selling_Price_in_lakhs'],index =index_data,columns=['car_model_range','km_Driven_range']).fillna(0).sort_values(by = ['Year','Name',],ascending=[True,True])

                                                                                                                                           Min_Selling_Price_in_lakhs  \
car_model_range                                                                                                                                       Fair(2016-2018)
km_Driven_range                                                                                                                                               10K-20K
Brand Year Name                                 km_Driven Seller_Type Owner        Mileage    Max_Power  Fuel   Engine  Seats Transmission
BMW   2010 BMW 5 Series 523i                    72200     Dealer      Second Owner 10.8 kmpl  150 bhp    Petrol 2497 CC 5     Automatic                           0.0
Audi  2011 Audi Q5 2.0 TDI                      120000    Individual  First Owner  12.8 kmpl  167.6 bhp  Diesel 1968 CC 5     Automatic                           0.0
BMW   2011 BMW X1 sDrive20d M Sport             42545     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic                           0.0
Audi  2013 Audi A6 2.0 TDI  Design Edition      50000     Dealer      First Owner  18.53 kmpl 187.74 bhp Diesel 1968 CC 5     Automatic                           0.0
           Audi A6 2.0 TDI Technology           33900     Dealer      Second Owner 17.68 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic                           0.0
BMW   2013 BMW X6 xDrive30d                     56000     Dealer      First Owner  11.2 kmpl  241 bhp    Diesel 2993 CC 4     Automatic                           0.0
Audi  2014 Audi A4 2.0 TDI                      44000     Individual  Second Owner 16.55 kmpl 147.51 bhp Diesel 1968 CC 5     Automatic                           0.0
      2015 Audi Q7 35 TDI Quattro Premium       53000     Dealer      First Owner  12.07 kmpl 241.4 bhp  Diesel 2967 CC 7     Automatic                           0.0
BMW   2016 BMW 3 Series 320d Luxury Line        30000     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                           0.0
           BMW 5 Series 520d Luxury Line        12000     Dealer      First Owner  18.12 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                          29.0
           BMW X1 sDrive20i xLine               30000     Individual  Second Owner 15.71 kmpl 189 bhp    Petrol 1998 CC 5     Automatic                           0.0
Audi  2017 Audi Q3 2.0 TDI Quattro Premium Plus 22000     Dealer      First Owner  15.73 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic                           0.0
BMW   2017 BMW 3 Series 320d                    13663     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                          32.0
Audi  2018 Audi Q5 35TDI Premium Plus           31800     Dealer      First Owner  17.01 kmpl 188 bhp    Diesel 1968 CC 5     Automatic                           0.0
BMW   2018 BMW 5 Series 520d Sport Line         29500     Dealer      First Owner  22.48 kmpl 187.74 bhp Diesel 1995 CC 5     Automatic                           0.0
           BMW 6 Series GT 630d Luxury Line     28156     Dealer      First Owner  17.09 kmpl 261.4 bhp  Diesel 2993 CC 4     Automatic                           0.0
           BMW X1 sDrive20d M Sport             18000     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic                          33.5
      2019 BMW X4 M Sport X xDrive20d           7500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                           0.0
                                                8500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                           0.0

                                                                                                                                                    \
car_model_range
km_Driven_range                                                                                                                            20K-40K
Brand Year Name                                 km_Driven Seller_Type Owner        Mileage    Max_Power  Fuel   Engine  Seats Transmission
BMW   2010 BMW 5 Series 523i                    72200     Dealer      Second Owner 10.8 kmpl  150 bhp    Petrol 2497 CC 5     Automatic       0.00
Audi  2011 Audi Q5 2.0 TDI                      120000    Individual  First Owner  12.8 kmpl  167.6 bhp  Diesel 1968 CC 5     Automatic       0.00
BMW   2011 BMW X1 sDrive20d M Sport             42545     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic       0.00
Audi  2013 Audi A6 2.0 TDI  Design Edition      50000     Dealer      First Owner  18.53 kmpl 187.74 bhp Diesel 1968 CC 5     Automatic       0.00
           Audi A6 2.0 TDI Technology           33900     Dealer      Second Owner 17.68 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic       0.00
BMW   2013 BMW X6 xDrive30d                     56000     Dealer      First Owner  11.2 kmpl  241 bhp    Diesel 2993 CC 4     Automatic       0.00
Audi  2014 Audi A4 2.0 TDI                      44000     Individual  Second Owner 16.55 kmpl 147.51 bhp Diesel 1968 CC 5     Automatic       0.00
      2015 Audi Q7 35 TDI Quattro Premium       53000     Dealer      First Owner  12.07 kmpl 241.4 bhp  Diesel 2967 CC 7     Automatic       0.00
BMW   2016 BMW 3 Series 320d Luxury Line        30000     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      21.50
           BMW 5 Series 520d Luxury Line        12000     Dealer      First Owner  18.12 kmpl 190 bhp    Diesel 1995 CC 5     Automatic       0.00
           BMW X1 sDrive20i xLine               30000     Individual  Second Owner 15.71 kmpl 189 bhp    Petrol 1998 CC 5     Automatic      25.00
Audi  2017 Audi Q3 2.0 TDI Quattro Premium Plus 22000     Dealer      First Owner  15.73 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic      28.25
BMW   2017 BMW 3 Series 320d                    13663     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic       0.00
Audi  2018 Audi Q5 35TDI Premium Plus           31800     Dealer      First Owner  17.01 kmpl 188 bhp    Diesel 1968 CC 5     Automatic      39.75
BMW   2018 BMW 5 Series 520d Sport Line         29500     Dealer      First Owner  22.48 kmpl 187.74 bhp Diesel 1995 CC 5     Automatic      37.90
           BMW 6 Series GT 630d Luxury Line     28156     Dealer      First Owner  17.09 kmpl 261.4 bhp  Diesel 2993 CC 4     Automatic      60.00
           BMW X1 sDrive20d M Sport             18000     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic       0.00
      2019 BMW X4 M Sport X xDrive20d           7500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic       0.00
                                                8500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic       0.00

                                                                                                                                                                \
car_model_range                                                                                                                            Moderate(2012-2015)
km_Driven_range                                                                                                                                        20K-40K
Brand Year Name                                 km_Driven Seller_Type Owner        Mileage    Max_Power  Fuel   Engine  Seats Transmission
BMW   2010 BMW 5 Series 523i                    72200     Dealer      Second Owner 10.8 kmpl  150 bhp    Petrol 2497 CC 5     Automatic                    0.0
Audi  2011 Audi Q5 2.0 TDI                      120000    Individual  First Owner  12.8 kmpl  167.6 bhp  Diesel 1968 CC 5     Automatic                    0.0
BMW   2011 BMW X1 sDrive20d M Sport             42545     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic                    0.0
Audi  2013 Audi A6 2.0 TDI  Design Edition      50000     Dealer      First Owner  18.53 kmpl 187.74 bhp Diesel 1968 CC 5     Automatic                    0.0
           Audi A6 2.0 TDI Technology           33900     Dealer      Second Owner 17.68 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic                   17.5
BMW   2013 BMW X6 xDrive30d                     56000     Dealer      First Owner  11.2 kmpl  241 bhp    Diesel 2993 CC 4     Automatic                    0.0
Audi  2014 Audi A4 2.0 TDI                      44000     Individual  Second Owner 16.55 kmpl 147.51 bhp Diesel 1968 CC 5     Automatic                    0.0
      2015 Audi Q7 35 TDI Quattro Premium       53000     Dealer      First Owner  12.07 kmpl 241.4 bhp  Diesel 2967 CC 7     Automatic                    0.0
BMW   2016 BMW 3 Series 320d Luxury Line        30000     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                    0.0
           BMW 5 Series 520d Luxury Line        12000     Dealer      First Owner  18.12 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                    0.0
           BMW X1 sDrive20i xLine               30000     Individual  Second Owner 15.71 kmpl 189 bhp    Petrol 1998 CC 5     Automatic                    0.0
Audi  2017 Audi Q3 2.0 TDI Quattro Premium Plus 22000     Dealer      First Owner  15.73 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic                    0.0
BMW   2017 BMW 3 Series 320d                    13663     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                    0.0
Audi  2018 Audi Q5 35TDI Premium Plus           31800     Dealer      First Owner  17.01 kmpl 188 bhp    Diesel 1968 CC 5     Automatic                    0.0
BMW   2018 BMW 5 Series 520d Sport Line         29500     Dealer      First Owner  22.48 kmpl 187.74 bhp Diesel 1995 CC 5     Automatic                    0.0
           BMW 6 Series GT 630d Luxury Line     28156     Dealer      First Owner  17.09 kmpl 261.4 bhp  Diesel 2993 CC 4     Automatic                    0.0
           BMW X1 sDrive20d M Sport             18000     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic                    0.0
      2019 BMW X4 M Sport X xDrive20d           7500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                    0.0
                                                8500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic                    0.0

                                                                                                                                                      \
car_model_range
km_Driven_range                                                                                                                              40K-80K
Brand Year Name                                 km_Driven Seller_Type Owner        Mileage    Max_Power  Fuel   Engine  Seats Transmission
BMW   2010 BMW 5 Series 523i                    72200     Dealer      Second Owner 10.8 kmpl  150 bhp    Petrol 2497 CC 5     Automatic      0.00000
Audi  2011 Audi Q5 2.0 TDI                      120000    Individual  First Owner  12.8 kmpl  167.6 bhp  Diesel 1968 CC 5     Automatic      0.00000
BMW   2011 BMW X1 sDrive20d M Sport             42545     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic      0.00000
Audi  2013 Audi A6 2.0 TDI  Design Edition      50000     Dealer      First Owner  18.53 kmpl 187.74 bhp Diesel 1968 CC 5     Automatic     16.89999
           Audi A6 2.0 TDI Technology           33900     Dealer      Second Owner 17.68 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic      0.00000
BMW   2013 BMW X6 xDrive30d                     56000     Dealer      First Owner  11.2 kmpl  241 bhp    Diesel 2993 CC 4     Automatic     37.50000
Audi  2014 Audi A4 2.0 TDI                      44000     Individual  Second Owner 16.55 kmpl 147.51 bhp Diesel 1968 CC 5     Automatic     16.00000
      2015 Audi Q7 35 TDI Quattro Premium       53000     Dealer      First Owner  12.07 kmpl 241.4 bhp  Diesel 2967 CC 7     Automatic     26.50000
BMW   2016 BMW 3 Series 320d Luxury Line        30000     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.00000
           BMW 5 Series 520d Luxury Line        12000     Dealer      First Owner  18.12 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.00000
           BMW X1 sDrive20i xLine               30000     Individual  Second Owner 15.71 kmpl 189 bhp    Petrol 1998 CC 5     Automatic      0.00000
Audi  2017 Audi Q3 2.0 TDI Quattro Premium Plus 22000     Dealer      First Owner  15.73 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic      0.00000
BMW   2017 BMW 3 Series 320d                    13663     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.00000
Audi  2018 Audi Q5 35TDI Premium Plus           31800     Dealer      First Owner  17.01 kmpl 188 bhp    Diesel 1968 CC 5     Automatic      0.00000
BMW   2018 BMW 5 Series 520d Sport Line         29500     Dealer      First Owner  22.48 kmpl 187.74 bhp Diesel 1995 CC 5     Automatic      0.00000
           BMW 6 Series GT 630d Luxury Line     28156     Dealer      First Owner  17.09 kmpl 261.4 bhp  Diesel 2993 CC 4     Automatic      0.00000
           BMW X1 sDrive20d M Sport             18000     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic      0.00000
      2019 BMW X4 M Sport X xDrive20d           7500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.00000
                                                8500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.00000

                                                                                                                                                       \
car_model_range                                                                                                                            New(2019+)
km_Driven_range                                                                                                                                5K-10K
Brand Year Name                                 km_Driven Seller_Type Owner        Mileage    Max_Power  Fuel   Engine  Seats Transmission
BMW   2010 BMW 5 Series 523i                    72200     Dealer      Second Owner 10.8 kmpl  150 bhp    Petrol 2497 CC 5     Automatic      0.000000
Audi  2011 Audi Q5 2.0 TDI                      120000    Individual  First Owner  12.8 kmpl  167.6 bhp  Diesel 1968 CC 5     Automatic      0.000000
BMW   2011 BMW X1 sDrive20d M Sport             42545     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic      0.000000
Audi  2013 Audi A6 2.0 TDI  Design Edition      50000     Dealer      First Owner  18.53 kmpl 187.74 bhp Diesel 1968 CC 5     Automatic      0.000000
           Audi A6 2.0 TDI Technology           33900     Dealer      Second Owner 17.68 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic      0.000000
BMW   2013 BMW X6 xDrive30d                     56000     Dealer      First Owner  11.2 kmpl  241 bhp    Diesel 2993 CC 4     Automatic      0.000000
Audi  2014 Audi A4 2.0 TDI                      44000     Individual  Second Owner 16.55 kmpl 147.51 bhp Diesel 1968 CC 5     Automatic      0.000000
      2015 Audi Q7 35 TDI Quattro Premium       53000     Dealer      First Owner  12.07 kmpl 241.4 bhp  Diesel 2967 CC 7     Automatic      0.000000
BMW   2016 BMW 3 Series 320d Luxury Line        30000     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.000000
           BMW 5 Series 520d Luxury Line        12000     Dealer      First Owner  18.12 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.000000
           BMW X1 sDrive20i xLine               30000     Individual  Second Owner 15.71 kmpl 189 bhp    Petrol 1998 CC 5     Automatic      0.000000
Audi  2017 Audi Q3 2.0 TDI Quattro Premium Plus 22000     Dealer      First Owner  15.73 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic      0.000000
BMW   2017 BMW 3 Series 320d                    13663     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic      0.000000
Audi  2018 Audi Q5 35TDI Premium Plus           31800     Dealer      First Owner  17.01 kmpl 188 bhp    Diesel 1968 CC 5     Automatic      0.000000
BMW   2018 BMW 5 Series 520d Sport Line         29500     Dealer      First Owner  22.48 kmpl 187.74 bhp Diesel 1995 CC 5     Automatic      0.000000
           BMW 6 Series GT 630d Luxury Line     28156     Dealer      First Owner  17.09 kmpl 261.4 bhp  Diesel 2993 CC 4     Automatic      0.000000
           BMW X1 sDrive20d M Sport             18000     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic      0.000000
      2019 BMW X4 M Sport X xDrive20d           7500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic     54.444444
                                                8500      Dealer      First Owner  16.78 kmpl 190 bhp    Diesel 1995 CC 5     Automatic     55.000000

                                                                                                                                                           \
car_model_range                                                                                                                            Old(2006-2011)
km_Driven_range                                                                                                                                   40K-80K
Brand Year Name                                 km_Driven Seller_Type Owner        Mileage    Max_Power  Fuel   Engine  Seats Transmission
BMW   2010 BMW 5 Series 523i                    72200     Dealer      Second Owner 10.8 kmpl  150 bhp    Petrol 2497 CC 5     Automatic              9.75
Audi  2011 Audi Q5 2.0 TDI                      120000    Individual  First Owner  12.8 kmpl  167.6 bhp  Diesel 1968 CC 5     Automatic              0.00
BMW   2011 BMW X1 sDrive20d M Sport             42545     Dealer      First Owner  19.62 kmpl 190 bhp    Diesel 1998 CC 5     Automatic             10.75
Audi  2013 Audi A6 2.0 TDI  Design Edition      50000     Dealer      First Owner  18.53 kmpl 187.74 bhp Diesel 1968 CC 5     Automatic              0.00
           Audi A6 2.0 TDI Technology           33900     Dealer      Second Owner 17.68 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic              0.00
BMW   2013 BMW X6 xDrive30d                     56000     Dealer      First Owner  11.2 kmpl  241 bhp    Diesel 2993 CC 4     Automatic              0.00
Audi  2014 Audi A4 2.0 TDI                      44000     Individual  Second Owner 16.55 kmpl 147.51 bhp Diesel 1968 CC 5     Automatic              0.00
      2015 Audi Q7 35 TDI Quattro Premium       53000     Dealer      First Owner  12.07 kmpl 241.4 bhp  Diesel 2967 CC 7     Automatic              0.00
BMW   2016 BMW 3 Series 320d Luxury Line        30000     Dealer      First Owner  22.69 kmpl 190 bhp    Diesel 1995 CC 5     Automatic              0.00
           BMW 5 Series 520d Luxury Line        12000     Dealer      First Owner  18.12 kmpl 190 bhp    Diesel 1995 CC 5     Automatic              0.00
           BMW X1 sDrive20i xLine               30000     Individual  Second Owner 15.71 kmpl 189 bhp    Petrol 1998 CC 5     Automatic              0.00
Audi  2017 Audi Q3 2.0 TDI Quattro Premium Plus 22000     Dealer      First Owner  15.73 kmpl 174.33 bhp Diesel 1968 CC 5     Automatic              0.00

#### Analysed for Big brands Audi and BMW and stored displayed using pivot table
#### Almost all cars are diesel and displayed minimum selling price w.r.t car model and km_driven range

In [288]:
# Most sold Brand Analysis ('Maruti')-- [Maruti,Petrol,Manual]
#Clearly Diesel cars have more price than Petrol cars and  Transmission automatic has high price..
index_data = ['Brand','Year','Name','km_Driven','Seller_Type','Owner','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
df_check_brand_min_Selling_price = df_min_selling_price.query("Brand=='Maruti' & Fuel=='Petrol' & Transmission=='Manual'")
pd.pivot_table(df_check_brand_min_Selling_price,values=['Min_Selling_Price_in_lakhs'],index =index_data,columns=['car_model_range','km_Driven_range']).fillna(0).sort_values(by = ['Year','Name',],ascending=[True,True])

                                                                                                                                 Min_Selling_Price_in_lakhs  \
car_model_range                                                                                                                          Antique(upto 1999)
km_Driven_range                                                                                                                                     20K-40K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                              0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                              0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                              0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                              0.4
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                              0.0
...                                                                                                                                                     ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual                              0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual                              0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual                              0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual                              0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual                              0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  40K-80K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.45
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.55
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.00
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.00
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.00
...                                                                                                                                  ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual          0.00
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual          0.00
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual          0.00
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual          0.00
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual          0.00

                                                                                                                                           \
car_model_range
km_Driven_range                                                                                                                  80K-160K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.00
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.00
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.52
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.00
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.00
...                                                                                                                                   ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual           0.00
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.00
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.00
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.00
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.00

                                                                                                                                                  \
car_model_range                                                                                                                  Fair(2016-2018)
km_Driven_range                                                                                                                             0-5K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                   0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                   0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                   0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                   0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual                   0.0
...                                                                                                                                          ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual                   0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual                   0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual                   0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual                   0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual                   0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  10K-20K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
...                                                                                                                                  ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.0

                                                                                                                                            \
car_model_range
km_Driven_range                                                                                                                  200K-250K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual             0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual             0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual             0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual             0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual             0.0
...                                                                                                                                    ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual             0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual             0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual             0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual             0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual             0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  20K-40K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
...                                                                                                                                  ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  40K-80K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual           0.0
...                                                                                                                                  ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual           0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual           0.0

                                                                                                                                         \
car_model_range
km_Driven_range                                                                                                                  5K-10K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual          0.0
...                                                                                                                                 ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual          0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual          0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual          0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual          0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual          0.0

                                                                                                                                           \
car_model_range
km_Driven_range                                                                                                                  80K-160K
Brand  Year Name                       km_Driven Seller_Type Owner        Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 1994 Maruti 800 AC              60000     Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual            0.0
       1999 Maruti 800 AC              60000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual            0.0
            Maruti 800 DX              100000    Individual  First Owner  16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual            0.0
            Maruti 800 Std             40000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual            0.0
       2000 Maruti 800 AC              50000     Individual  Second Owner 16.1 kmpl  37 bhp    Petrol 796 CC  4     Manual            0.0
...                                                                                                                                   ...
       2020 Maruti Alto K10 VXI        6000      Individual  First Owner  23.95 kmpl 67.05 bhp Petrol 998 CC  5     Manual            0.0
            Maruti Baleno Delta        5000      Individual  First Owner  21.01 kmpl 81.80 bhp Petrol 1197 CC 5     Manual            0.0
            Maruti Celerio VXI         13000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual            0.0
            Maruti Celerio ZXI         25000     Individual  First Owner  21.63 kmpl 67.04 bhp Petrol 998 CC  5     Manual            0.0
            Maruti Swift Dzire VXI 1.2 1500      Individual  First Owner  21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Manual            0.0


#### displayed in pivot table for mostly sold car Maruti and

In [281]:
# Most sold Brand Analysis ('Maruti')-- [Maruti,Petrol,Automatic]
#Clearly Diesel cars have more price than Petrol cars and  Transmission automatic has high price..
index_data = ['Brand','Year','Name','Seller_Type','km_Driven','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
df_check_brand_min_Selling_price = df_min_selling_price.query("Brand=='Maruti' & Fuel=='Petrol' & Transmission=='Automatic'")
pd.pivot_table(df_check_brand_min_Selling_price,values=['Min_Selling_Price_in_lakhs'],index =index_data,columns=['car_model_range','km_Driven_range']).fillna(0).sort_values(by = ['Year','Name',],ascending=[True,True])

                                                                                                                               Min_Selling_Price_in_lakhs  \
car_model_range                                                                                                                           Fair(2016-2018)
km_Driven_range                                                                                                                                      0-5K
Brand  Year Name                             Seller_Type      km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2006 Maruti Wagon R AX                Individual       60000     18.9 kmpl  67.1 bhp  Petrol 998 CC  5     Automatic                           0.0
       2011 Maruti SX4 ZXI AT                Individual       65000     12.6 kmpl  103.3 bhp Petrol 1586 CC 5     Automatic                           0.0
       2012 Maruti Swift Dzire VXi AT        Individual       120000    17.4 kmpl  85.8 bhp  Petrol 1197 CC 5     Automatic                           0.0
       2015 Maruti Ciaz AT ZXi               Individual       30000     19.12 kmpl 91.1 bhp  Petrol 1373 CC 5     Automatic                           0.0
            Maruti Wagon R AMT VXI           Individual       50000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic                           0.0
       2016 Maruti Baleno Zeta Automatic     Individual       50000     21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic                           0.0
            Maruti Celerio ZXI AT            Individual       35000     23.1 kmpl  67.04 bhp Petrol 998 CC  5     Automatic                           0.0
       2017 Maruti Ignis 1.2 AMT Alpha BSIV  Dealer           57247     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
                                             Individual       40000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
       2018 Maruti Baleno Alpha Automatic    Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic                           8.3
            Maruti Swift AMT ZXI             Dealer           69779     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Swift Dzire AMT VXI BS IV Individual       7800      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Swift Dzire VXi AT        Dealer           23300     18.5 kmpl  83.14 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Wagon R AMT VXI           Individual       30000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic                           0.0
                                                              35000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic                           0.0
       2019 Maruti Baleno Zeta Automatic     Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic                           0.0
            Maruti Ignis 1.2 AMT Delta BSIV  Individual       20000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Swift AMT VVT VXI         Trustmark Dealer 5621      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Swift AMT VXI             Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Swift AMT ZXI Plus BSIV   Individual       20000     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                           0.0
            Maruti Swift Dzire AMT VXI       Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                           0.0

                                                                                                                                        \
car_model_range
km_Driven_range                                                                                                                20K-40K
Brand  Year Name                             Seller_Type      km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2006 Maruti Wagon R AX                Individual       60000     18.9 kmpl  67.1 bhp  Petrol 998 CC  5     Automatic       0.00
       2011 Maruti SX4 ZXI AT                Individual       65000     12.6 kmpl  103.3 bhp Petrol 1586 CC 5     Automatic       0.00
       2012 Maruti Swift Dzire VXi AT        Individual       120000    17.4 kmpl  85.8 bhp  Petrol 1197 CC 5     Automatic       0.00
       2015 Maruti Ciaz AT ZXi               Individual       30000     19.12 kmpl 91.1 bhp  Petrol 1373 CC 5     Automatic       0.00
            Maruti Wagon R AMT VXI           Individual       50000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic       0.00
       2016 Maruti Baleno Zeta Automatic     Individual       50000     21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic       0.00
            Maruti Celerio ZXI AT            Individual       35000     23.1 kmpl  67.04 bhp Petrol 998 CC  5     Automatic       4.00
       2017 Maruti Ignis 1.2 AMT Alpha BSIV  Dealer           57247     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.00
                                             Individual       40000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       5.50
       2018 Maruti Baleno Alpha Automatic    Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift AMT ZXI             Dealer           69779     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift Dzire AMT VXI BS IV Individual       7800      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift Dzire VXi AT        Dealer           23300     18.5 kmpl  83.14 bhp Petrol 1197 CC 5     Automatic       6.75
            Maruti Wagon R AMT VXI           Individual       30000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic       4.48
                                                              35000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic       4.20
       2019 Maruti Baleno Zeta Automatic     Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic       0.00
            Maruti Ignis 1.2 AMT Delta BSIV  Individual       20000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift AMT VVT VXI         Trustmark Dealer 5621      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift AMT VXI             Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift AMT ZXI Plus BSIV   Individual       20000     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.00
            Maruti Swift Dzire AMT VXI       Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.00

                                                                                                                                        \
car_model_range
km_Driven_range                                                                                                                40K-80K
Brand  Year Name                             Seller_Type      km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2006 Maruti Wagon R AX                Individual       60000     18.9 kmpl  67.1 bhp  Petrol 998 CC  5     Automatic        0.0
       2011 Maruti SX4 ZXI AT                Individual       65000     12.6 kmpl  103.3 bhp Petrol 1586 CC 5     Automatic        0.0
       2012 Maruti Swift Dzire VXi AT        Individual       120000    17.4 kmpl  85.8 bhp  Petrol 1197 CC 5     Automatic        0.0
       2015 Maruti Ciaz AT ZXi               Individual       30000     19.12 kmpl 91.1 bhp  Petrol 1373 CC 5     Automatic        0.0
            Maruti Wagon R AMT VXI           Individual       50000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic        0.0
       2016 Maruti Baleno Zeta Automatic     Individual       50000     21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic        6.5
            Maruti Celerio ZXI AT            Individual       35000     23.1 kmpl  67.04 bhp Petrol 998 CC  5     Automatic        0.0
       2017 Maruti Ignis 1.2 AMT Alpha BSIV  Dealer           57247     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        4.9
                                             Individual       40000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0
       2018 Maruti Baleno Alpha Automatic    Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift AMT ZXI             Dealer           69779     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic        6.0
            Maruti Swift Dzire AMT VXI BS IV Individual       7800      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift Dzire VXi AT        Dealer           23300     18.5 kmpl  83.14 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Wagon R AMT VXI           Individual       30000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic        0.0
                                                              35000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic        0.0
       2019 Maruti Baleno Zeta Automatic     Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic        0.0
            Maruti Ignis 1.2 AMT Delta BSIV  Individual       20000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift AMT VVT VXI         Trustmark Dealer 5621      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift AMT VXI             Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift AMT ZXI Plus BSIV   Individual       20000     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift Dzire AMT VXI       Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0

                                                                                                                                       \
car_model_range
km_Driven_range                                                                                                                5K-10K
Brand  Year Name                             Seller_Type      km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2006 Maruti Wagon R AX                Individual       60000     18.9 kmpl  67.1 bhp  Petrol 998 CC  5     Automatic       0.0
       2011 Maruti SX4 ZXI AT                Individual       65000     12.6 kmpl  103.3 bhp Petrol 1586 CC 5     Automatic       0.0
       2012 Maruti Swift Dzire VXi AT        Individual       120000    17.4 kmpl  85.8 bhp  Petrol 1197 CC 5     Automatic       0.0
       2015 Maruti Ciaz AT ZXi               Individual       30000     19.12 kmpl 91.1 bhp  Petrol 1373 CC 5     Automatic       0.0
            Maruti Wagon R AMT VXI           Individual       50000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic       0.0
       2016 Maruti Baleno Zeta Automatic     Individual       50000     21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic       0.0
            Maruti Celerio ZXI AT            Individual       35000     23.1 kmpl  67.04 bhp Petrol 998 CC  5     Automatic       0.0
       2017 Maruti Ignis 1.2 AMT Alpha BSIV  Dealer           57247     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.0
                                             Individual       40000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.0
       2018 Maruti Baleno Alpha Automatic    Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic       0.0
            Maruti Swift AMT ZXI             Dealer           69779     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.0
            Maruti Swift Dzire AMT VXI BS IV Individual       7800      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       7.0
            Maruti Swift Dzire VXi AT        Dealer           23300     18.5 kmpl  83.14 bhp Petrol 1197 CC 5     Automatic       0.0
            Maruti Wagon R AMT VXI           Individual       30000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic       0.0
                                                              35000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic       0.0
       2019 Maruti Baleno Zeta Automatic     Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic       0.0
            Maruti Ignis 1.2 AMT Delta BSIV  Individual       20000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.0
            Maruti Swift AMT VVT VXI         Trustmark Dealer 5621      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.0
            Maruti Swift AMT VXI             Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.0
            Maruti Swift AMT ZXI Plus BSIV   Individual       20000     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic       0.0
            Maruti Swift Dzire AMT VXI       Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic       0.0

                                                                                                                                                    \
car_model_range                                                                                                                Moderate(2012-2015)
km_Driven_range                                                                                                                            20K-40K
Brand  Year Name                             Seller_Type      km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2006 Maruti Wagon R AX                Individual       60000     18.9 kmpl  67.1 bhp  Petrol 998 CC  5     Automatic                   0.00
       2011 Maruti SX4 ZXI AT                Individual       65000     12.6 kmpl  103.3 bhp Petrol 1586 CC 5     Automatic                   0.00
       2012 Maruti Swift Dzire VXi AT        Individual       120000    17.4 kmpl  85.8 bhp  Petrol 1197 CC 5     Automatic                   0.00
       2015 Maruti Ciaz AT ZXi               Individual       30000     19.12 kmpl 91.1 bhp  Petrol 1373 CC 5     Automatic                   6.85
            Maruti Wagon R AMT VXI           Individual       50000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic                   0.00
       2016 Maruti Baleno Zeta Automatic     Individual       50000     21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic                   0.00
            Maruti Celerio ZXI AT            Individual       35000     23.1 kmpl  67.04 bhp Petrol 998 CC  5     Automatic                   0.00
       2017 Maruti Ignis 1.2 AMT Alpha BSIV  Dealer           57247     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
                                             Individual       40000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
       2018 Maruti Baleno Alpha Automatic    Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift AMT ZXI             Dealer           69779     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift Dzire AMT VXI BS IV Individual       7800      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift Dzire VXi AT        Dealer           23300     18.5 kmpl  83.14 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Wagon R AMT VXI           Individual       30000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic                   0.00
                                                              35000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic                   0.00
       2019 Maruti Baleno Zeta Automatic     Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic                   0.00
            Maruti Ignis 1.2 AMT Delta BSIV  Individual       20000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift AMT VVT VXI         Trustmark Dealer 5621      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift AMT VXI             Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift AMT ZXI Plus BSIV   Individual       20000     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic                   0.00
            Maruti Swift Dzire AMT VXI       Individual       10000     21.21 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic                   0.00

                                                                                                                                        \
car_model_range
km_Driven_range                                                                                                                40K-80K
Brand  Year Name                             Seller_Type      km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2006 Maruti Wagon R AX                Individual       60000     18.9 kmpl  67.1 bhp  Petrol 998 CC  5     Automatic        0.0
       2011 Maruti SX4 ZXI AT                Individual       65000     12.6 kmpl  103.3 bhp Petrol 1586 CC 5     Automatic        0.0
       2012 Maruti Swift Dzire VXi AT        Individual       120000    17.4 kmpl  85.8 bhp  Petrol 1197 CC 5     Automatic        0.0
       2015 Maruti Ciaz AT ZXi               Individual       30000     19.12 kmpl 91.1 bhp  Petrol 1373 CC 5     Automatic        0.0
            Maruti Wagon R AMT VXI           Individual       50000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic        3.9
       2016 Maruti Baleno Zeta Automatic     Individual       50000     21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic        0.0
            Maruti Celerio ZXI AT            Individual       35000     23.1 kmpl  67.04 bhp Petrol 998 CC  5     Automatic        0.0
       2017 Maruti Ignis 1.2 AMT Alpha BSIV  Dealer           57247     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0
                                             Individual       40000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0
       2018 Maruti Baleno Alpha Automatic    Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift AMT ZXI             Dealer           69779     22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift Dzire AMT VXI BS IV Individual       7800      22.0 kmpl  81.80 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Swift Dzire VXi AT        Dealer           23300     18.5 kmpl  83.14 bhp Petrol 1197 CC 5     Automatic        0.0
            Maruti Wagon R AMT VXI           Individual       30000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic        0.0
                                                              35000     20.51 kmpl 67 bhp    Petrol 998 CC  5     Automatic        0.0
       2019 Maruti Baleno Zeta Automatic     Individual       5000      21.4 kmpl  83.1 bhp  Petrol 1197 CC 5     Automatic        0.0
            Maruti Ignis 1.2 AMT Delta BSIV  Individual       20000     20.89 kmpl 81.80 bhp Petrol 1197 CC 5     Automatic        0.0

- Sample
- Sample1

In [156]:
df_min_selling_price.Brand.unique()

array(['Audi', 'BMW', 'Chevrolet', 'Daewoo', 'Datsun', 'Fiat', 'Force',
       'Ford', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Kia', 'Land',
       'Lexus', 'MG', 'Mahindra', 'Maruti', 'Mercedes-Benz', 'Mitsubishi',
       'Nissan', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [168]:
df_min_selling_price.Seller_Type.unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [290]:
# Most sold Brand Analysis ('Maruti') -- [Maruti,Diesel,Manual]
#Clearly Diesel cars have more price with Transmission Automatic..
index_data = ['Brand','Year','Name','Seller_Type','km_Driven','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
df_check_brand_min_Selling_price = df_min_selling_price.query("Brand=='Maruti' & Fuel=='Diesel' & Transmission=='Manual'")
pd.pivot_table(df_check_brand_min_Selling_price,values=['Min_Selling_Price_in_lakhs'],index =index_data,columns=['car_model_range','km_Driven_range']).fillna(0).sort_values(by = ['Year','Name',],ascending=[True,True])

                                                                                                                        Min_Selling_Price_in_lakhs  \
car_model_range                                                                                                                    Fair(2016-2018)
km_Driven_range                                                                                                                               0-5K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual                              0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual                              0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual                              0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual                              0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual                              0.0
...                                                                                                                                            ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual                              0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual                              0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual                              0.0

                                                                                                                                 \
car_model_range
km_Driven_range                                                                                                         10K-20K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual           0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
...                                                                                                                         ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0

                                                                                                                                 \
car_model_range
km_Driven_range                                                                                                         20K-40K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual           0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
...                                                                                                                         ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0

                                                                                                                                 \
car_model_range
km_Driven_range                                                                                                         40K-80K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual           0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
...                                                                                                                         ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           7.7
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           9.5
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0

                                                                                                                                  \
car_model_range
km_Driven_range                                                                                                         80K-160K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual            0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual            0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual            0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual            0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual            0.0
...                                                                                                                          ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual            0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual            0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual            0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual            0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual            0.0

                                                                                                                                             \
car_model_range                                                                                                         Moderate(2012-2015)
km_Driven_range                                                                                                                     10K-20K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual                       0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual                       0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual                       0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual                       0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual                       0.0
...                                                                                                                                     ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual                       0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual                       0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual                       0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual                       0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual                       0.0

                                                                                                                                   \
car_model_range
km_Driven_range                                                                                                         160K-200K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual             0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual             0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual             0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual             0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual             0.0
...                                                                                                                           ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual             0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual             0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual             0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual             0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual             0.0

                                                                                                                                 \
car_model_range
km_Driven_range                                                                                                         20K-40K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual           0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
...                                                                                                                         ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0

                                                                                                                                 \
car_model_range
km_Driven_range                                                                                                         40K-80K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual           0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual           0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual           0.0
...                                                                                                                         ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual           0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual           0.0

                                                                                                                                  \
car_model_range
km_Driven_range                                                                                                         80K-160K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual            0.0
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual            0.0
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual            0.0
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual            0.0
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual            0.0
...                                                                                                                          ...
       2018 Maruti Vitara Brezza VDi Option Individual  50000     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual            0.0
            Maruti Vitara Brezza ZDi        Dealer      58511     24.3 kmpl 88.5 bhp  Diesel 1248 CC 5     Manual            0.0
       2019 Maruti Swift Dzire VDI          Individual  24000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual            0.0
                                                        25000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual            0.0
                                                        30000     28.4 kmpl 74.02 bhp Diesel 1248 CC 5     Manual            0.0

                                                                                                                                    \
car_model_range                                                                                                         New(2019+)
km_Driven_range                                                                                                            20K-40K
Brand  Year Name                            Seller_Type km_Driven Mileage   Max_Power Fuel   Engine  Seats Transmission
Maruti 2003 Maruti Zen D                    Individual  120000    20.8 kmpl 58 bhp    Diesel 1527 CC 5     Manual             0.00
       2008 Maruti Swift Dzire LDi          Individual  80000     19.3 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual             0.00
            Maruti Swift Ldi BSIII          Individual  100000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual             0.00
                                                        120000    17.8 kmpl 75 bhp    Diesel 1248 CC 5     Manual             0.00
       2009 Maruti Ritz VDi                 Individual  85000     21.1 kmpl 73.9 bhp  Diesel 1248 CC 5     Manual             0.00

In [289]:
# Most sold Brand Analysis ('Maruti') -- [Maruti,Diesel,Automatic]
#Clearly Diesel cars have more price with Transmission Automatic..
index_data = ['Brand','Year','Name','Seller_Type','km_Driven','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
df_check_brand_min_Selling_price = df_min_selling_price.query("Brand=='Maruti' & Fuel=='Diesel' & Transmission=='Automatic'")
pd.pivot_table(df_check_brand_min_Selling_price,values=['Min_Selling_Price_in_lakhs'],index =index_data,columns=['car_model_range','km_Driven_range']).fillna(0).sort_values(by = ['Year','Name',],ascending=[True,True])

                                                                                                                                     Min_Selling_Price_in_lakhs  \
car_model_range                                                                                                                                 Fair(2016-2018)
km_Driven_range                                                                                                                                         10K-20K
Brand  Year Name                                        Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Swift Dzire AMT ZDI                  Individual  50000     26.59 kmpl 74 bhp    Diesel 1248 CC 5     Automatic                           0.0
       2017 Maruti Ignis 1.3 AMT Zeta                   Individual  37000     26.8 kmpl  74 bhp    Diesel 1248 CC 5     Automatic                           0.0
            Maruti Swift Dzire AMT VDI                  Individual  19000     28.4 kmpl  74.02 bhp Diesel 1248 CC 5     Automatic                           7.5
       2018 Maruti Vitara Brezza ZDi Plus AMT Dual Tone Individual  35000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic                           0.0
       2019 Maruti Vitara Brezza ZDi Plus AMT           Individual  9850      24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic                           0.0

                                                                                                                                              \
car_model_range
km_Driven_range                                                                                                                      20K-40K
Brand  Year Name                                        Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Swift Dzire AMT ZDI                  Individual  50000     26.59 kmpl 74 bhp    Diesel 1248 CC 5     Automatic       0.00
       2017 Maruti Ignis 1.3 AMT Zeta                   Individual  37000     26.8 kmpl  74 bhp    Diesel 1248 CC 5     Automatic       6.25
            Maruti Swift Dzire AMT VDI                  Individual  19000     28.4 kmpl  74.02 bhp Diesel 1248 CC 5     Automatic       0.00
       2018 Maruti Vitara Brezza ZDi Plus AMT Dual Tone Individual  35000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic       8.33
       2019 Maruti Vitara Brezza ZDi Plus AMT           Individual  9850      24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic       0.00

                                                                                                                                              \
car_model_range
km_Driven_range                                                                                                                      40K-80K
Brand  Year Name                                        Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Swift Dzire AMT ZDI                  Individual  50000     26.59 kmpl 74 bhp    Diesel 1248 CC 5     Automatic        6.5
       2017 Maruti Ignis 1.3 AMT Zeta                   Individual  37000     26.8 kmpl  74 bhp    Diesel 1248 CC 5     Automatic        0.0
            Maruti Swift Dzire AMT VDI                  Individual  19000     28.4 kmpl  74.02 bhp Diesel 1248 CC 5     Automatic        0.0
       2018 Maruti Vitara Brezza ZDi Plus AMT Dual Tone Individual  35000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic        0.0
       2019 Maruti Vitara Brezza ZDi Plus AMT           Individual  9850      24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic        0.0


car_model_range                                                                                                                      New(2019+)
km_Driven_range                                                                                                                          5K-10K
Brand  Year Name                                        Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Swift Dzire AMT ZDI                  Individual  50000     26.59 kmpl 74 bhp    Diesel 1248 CC 5     Automatic          0.00
       2017 Maruti Ignis 1.3 AMT Zeta                   Individual  37000     26.8 kmpl  74 bhp    Diesel 1248 CC 5     Automatic          0.00
            Maruti Swift Dzire AMT VDI                  Individual  19000     28.4 kmpl  74.02 bhp Diesel 1248 CC 5     Automatic          0.00
       2018 Maruti Vitara Brezza ZDi Plus AMT Dual Tone Individual  35000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic          0.00
       2019 Maruti Vitara Brezza ZDi Plus AMT           Individual  9850      24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Automatic         10.25

In [291]:
#df_check_brand_min_Selling_price.km_Driven_range = df_check_brand_min_Selling_price.km_Driven_range.astype('object')
#km_Driven_range
#car_model_range
df_check_brand_min_Selling_price.dtypes

Brand                          object
Year                            int64
Name                           object
Region                         object
State_Name                     object
City_Name                      object
Seller_Type                    object
km_Driven                       int64
Fuel                           object
Engine                         object
Seats                           int64
Transmission                   object
Owner                          object
Mileage                        object
Max_Power                      object
Min_Selling_Price_in_lakhs    float64
km_Driven_range                object
car_model_range                object
approx_Mileage                 object
dtype: object

In [245]:
input_dict = {'Brand':'Maruti','Fuel':'Diesel','approx_Mileage':'25.0'}

In [292]:
#Amalysis of min selling price for varius model from user inputs...

df_input_used_cars_rep = df_min_selling_price[(df_min_selling_price[''.join(list(input_dict.keys())[0])]==''.join(list(input_dict.values())[0])) & (df_min_selling_price[''.join(list(input_dict.keys())[1])]==''.join(list(input_dict.values())[1])) & (df_min_selling_price[''.join(list(input_dict.keys())[2])]==''.join(list(input_dict.values())[2]))]

In [293]:
df_input_used_cars_rep.head(5)

,Brand,Year,Name,Region,State_Name,City_Name,Seller_Type,km_Driven,Fuel,Engine,Seats,Transmission,Owner,Mileage,Max_Power,Min_Selling_Price_in_lakhs,km_Driven_range,car_model_range,approx_Mileage
1405,Maruti,2018,Maruti Ertiga 1.5 VDI,South,Karnataka,Mangalore,Individual,59000,Diesel,1498 CC,7,Manual,First Owner,24.2 kmpl,93.87 bhp,8.50,40K-80K,Fair(2016-2018),25.0
1275,Maruti,2016,Maruti Ertiga SHVS LDI Option,South,Kerala,Kochi,Individual,70000,Diesel,1248 CC,7,Manual,Second Owner,24.52 kmpl,88.5 bhp,7.56,40K-80K,Fair(2016-2018),25.0
1277,Maruti,2016,Maruti Ertiga SHVS VDI,South,Kerala,Kochi,Individual,70000,Diesel,1248 CC,7,Manual,Second Owner,24.52 kmpl,88.5 bhp,7.78,40K-80K,Fair(2016-2018),25.0
1276,Maruti,2016,Maruti Ertiga SHVS VDI,South,Karnataka,Mangalore,Individual,80000,Diesel,1248 CC,7,Manual,First Owner,24.52 kmpl,88.5 bhp,7.50,40K-80K,Fair(2016-2018),25.0
1330,Maruti,2017,Maruti Ertiga SHVS VDI,South,Kerala,Kochi,Individual,80000,Diesel,1248 CC,7,Manual,First Owner,24.52 kmpl,88.5 bhp,7.20,40K-80K,Fair(2016-2018),25.0

In [294]:
input_check = ['Brand','Year','Name','Seller_Type','km_Driven','Mileage','Max_Power','Fuel','Engine','Seats','Transmission']
pd.pivot_table(df_input_used_cars_rep,values=['Min_Selling_Price_in_lakhs'],index =input_check,columns=['car_model_range','km_Driven_range']).head(10).fillna(0).sort_values(by =['Year','Name'],ascending=[True,True])

                                                                                                                                 Min_Selling_Price_in_lakhs  \
car_model_range                                                                                                                             Fair(2016-2018)
km_Driven_range                                                                                                                                        0-5K
Brand  Year Name                                    Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Ertiga SHVS LDI Option           Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual                              0.0
            Maruti Ertiga SHVS VDI                  Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual                              0.0
                                                                80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual                              0.0
            Maruti Ertiga SHVS ZDI Plus             Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual                              0.0
            Maruti Vitara Brezza VDi                Individual  70000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
            Maruti Vitara Brezza ZDi Plus           Dealer      63000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
            Maruti Vitara Brezza ZDi Plus Dual Tone Individual  60000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
                                                                90000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
                                                                110000    24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual                              0.0
       2017 Maruti Ertiga SHVS VDI                  Individual  80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual                              0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  10K-20K
Brand  Year Name                                    Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Ertiga SHVS LDI Option           Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
            Maruti Ertiga SHVS VDI                  Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
                                                                80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
            Maruti Ertiga SHVS ZDI Plus             Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
            Maruti Vitara Brezza VDi                Individual  70000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi Plus           Dealer      63000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi Plus Dual Tone Individual  60000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
                                                                90000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
                                                                110000    24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
       2017 Maruti Ertiga SHVS VDI                  Individual  80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  20K-40K
Brand  Year Name                                    Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Ertiga SHVS LDI Option           Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
            Maruti Ertiga SHVS VDI                  Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
                                                                80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
            Maruti Ertiga SHVS ZDI Plus             Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0
            Maruti Vitara Brezza VDi                Individual  70000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi Plus           Dealer      63000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
            Maruti Vitara Brezza ZDi Plus Dual Tone Individual  60000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
                                                                90000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
                                                                110000    24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual           0.0
       2017 Maruti Ertiga SHVS VDI                  Individual  80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual           0.0

                                                                                                                                          \
car_model_range
km_Driven_range                                                                                                                  40K-80K
Brand  Year Name                                    Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Ertiga SHVS LDI Option           Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual          7.56
            Maruti Ertiga SHVS VDI                  Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual          7.78
                                                                80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual          7.50
            Maruti Ertiga SHVS ZDI Plus             Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual         10.00
            Maruti Vitara Brezza VDi                Individual  70000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual          7.45
            Maruti Vitara Brezza ZDi Plus           Dealer      63000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual          8.39
            Maruti Vitara Brezza ZDi Plus Dual Tone Individual  60000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual          7.80
                                                                90000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual          0.00
                                                                110000    24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual          0.00
       2017 Maruti Ertiga SHVS VDI                  Individual  80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual          7.20

                                                                                                                                           \
car_model_range
km_Driven_range                                                                                                                  80K-160K
Brand  Year Name                                    Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Ertiga SHVS LDI Option           Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual            0.0
            Maruti Ertiga SHVS VDI                  Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual            0.0
                                                                80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual            0.0
            Maruti Ertiga SHVS ZDI Plus             Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual            0.0
            Maruti Vitara Brezza VDi                Individual  70000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual            0.0
            Maruti Vitara Brezza ZDi Plus           Dealer      63000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual            0.0
            Maruti Vitara Brezza ZDi Plus Dual Tone Individual  60000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual            0.0
                                                                90000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual            8.0
                                                                110000    24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual            7.0
       2017 Maruti Ertiga SHVS VDI                  Individual  80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual            0.0


car_model_range                                                                                                                  New(2019+)
km_Driven_range                                                                                                                      5K-10K
Brand  Year Name                                    Seller_Type km_Driven Mileage    Max_Power Fuel   Engine  Seats Transmission
Maruti 2016 Maruti Ertiga SHVS LDI Option           Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual              0.0
            Maruti Ertiga SHVS VDI                  Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual              0.0
                                                                80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual              0.0
            Maruti Ertiga SHVS ZDI Plus             Individual  70000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual              0.0
            Maruti Vitara Brezza VDi                Individual  70000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual              0.0
            Maruti Vitara Brezza ZDi Plus           Dealer      63000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual              0.0
            Maruti Vitara Brezza ZDi Plus Dual Tone Individual  60000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual              0.0
                                                                90000     24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual              0.0
                                                                110000    24.3 kmpl  88.5 bhp  Diesel 1248 CC 5     Manual              0.0
       2017 Maruti Ertiga SHVS VDI                  Individual  80000     24.52 kmpl 88.5 bhp  Diesel 1248 CC 7     Manual              0.0